"""add models

Revision ID: 7fa55628a2e8
Revises: 
Create Date: 2021-10-28 12:00:31.443015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa55628a2e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familyMemId', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=45), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familyMemId'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familyMemId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familyMemId'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profits')
    op.drop_table('costs')
    op.drop_table('family')
    # ### end Alembic commands ###
