"""add models

Revision ID: edc921ef0062
Revises: 
Create Date: 2021-11-02 11:31:34.444287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc921ef0062'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familyId', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=30), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['familyId'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familyMemId', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=45), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familyMemId'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familyMemId', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familyMemId'], ['family_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profits')
    op.drop_table('costs')
    op.drop_table('family_members')
    op.drop_table('family')
    # ### end Alembic commands ###
